Prompt Foreign Key Constraints on Table A_ATTIKI_STOP_SEMS_DIM;
ALTER TABLE A_ATTIKI_STOP_SEMS_DIM ADD (
  CONSTRAINT STOP_SEMS_POI_DIM 
 FOREIGN KEY (POI_ID) 
 REFERENCES A_ATTIKI_SPACE_DIM (POI_ID))
/
