Prompt Non-Foreign Key Constraints on Table A_ATTIKI_MOVES_FACT;
ALTER TABLE A_ATTIKI_MOVES_FACT ADD (
  CONSTRAINT MOVES_FACT_PK
 PRIMARY KEY
 (PERIOD_ID, FROM_STOP_SEMS_ID, TO_STOP_SEMS_ID, USER_PROFILE_ID, MOVE_SEMS_ID))
/
