Prompt Non-Foreign Key Constraints on Table ATTIKI_200_MOVES_FACT;
ALTER TABLE ATTIKI_200_MOVES_FACT ADD (
  CONSTRAINT ATTIKI_200_MOVES_FACT_PK
 PRIMARY KEY
 (PERIOD_ID, FROM_STOP_SEMS_ID, TO_STOP_SEMS_ID, USER_PROFILE_ID, MOVE_SEMS_ID))
/
