Prompt Non-Foreign Key Constraints on Table ATTIKI_200_STOP_SEMS_DIM;
ALTER TABLE ATTIKI_200_STOP_SEMS_DIM ADD (
  CONSTRAINT ATTIKI_200_STOPS_SEMS_PK
 PRIMARY KEY
 (STOP_SEMS_ID)
    USING INDEX 
    TABLESPACE USERS)
/
