Prompt Foreign Key Constraints on Table ATTIKI_200_STOPS_FACT;
ALTER TABLE ATTIKI_200_STOPS_FACT ADD (
  CONSTRAINT ATTIKI_200_STOPS_STOP_SEMS_FK 
 FOREIGN KEY (STOP_SEMS_ID) 
 REFERENCES ATTIKI_200_STOP_SEMS_DIM (STOP_SEMS_ID),
  CONSTRAINT ATTIKI_200_STOPS_PERIOD_FK 
 FOREIGN KEY (PERIOD_ID) 
 REFERENCES ATTIKI_200_PERIOD_DIM (PERIOD_ID),
  CONSTRAINT ATTIKI_200_STOPS_USER_FK 
 FOREIGN KEY (USER_PROFILE_ID) 
 REFERENCES ATTIKI_200_USERS_DIM (USER_PROFILE_ID))
/
