Prompt Non-Foreign Key Constraints on Table ATTIKI_CENTER_FACTTBL;
ALTER TABLE ATTIKI_CENTER_FACTTBL ADD (
  CONSTRAINT ATTIKI_CENTER_FACTTBL_IX
 PRIMARY KEY
 (TIME_ID, SPACE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
