Prompt Foreign Key Constraints on Table ATTIKI_200_STOP_SEMS_DIM;
ALTER TABLE ATTIKI_200_STOP_SEMS_DIM ADD (
  CONSTRAINT ATTIKI_200_STOP_SEMS_POI_DIM 
 FOREIGN KEY (POI_ID) 
 REFERENCES ATTIKI_200_SPACE_DIM (POI_ID))
/
