Prompt Non-Foreign Key Constraints on Table HS1D4P200_STOPS_FACT;
ALTER TABLE HS1D4P200_STOPS_FACT ADD (
  CONSTRAINT HS1D4P200_STOPS_FACT_PK
 PRIMARY KEY
 (PERIOD_ID, STOP_SEMS_ID, USER_PROFILE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
