Prompt Foreign Key Constraints on Table HS1D4P50_STOP_SEMS_DIM;
ALTER TABLE HS1D4P50_STOP_SEMS_DIM ADD (
  CONSTRAINT HS1D4P50_STOP_SEMS_POI_DIM 
 FOREIGN KEY (POI_ID) 
 REFERENCES HS1D4P50_SPACE_DIM (POI_ID))
/
