Prompt Non-Foreign Key Constraints on Table HS1D4P150_TIME_DIM;
ALTER TABLE HS1D4P150_TIME_DIM ADD (
  CONSTRAINT HS1D4P150_TIME_DIM_PK
 PRIMARY KEY
 (TIME_ID)
    USING INDEX 
    TABLESPACE USERS)
/
