Prompt Non-Foreign Key Constraints on Table HS1D4P150_SPACE_DIM;
ALTER TABLE HS1D4P150_SPACE_DIM ADD (
  CONSTRAINT HS1D4P150_SPACE_DIM_PK
 PRIMARY KEY
 (POI_ID)
    USING INDEX 
    TABLESPACE USERS)
/
