Prompt Non-Foreign Key Constraints on Table HS1D4P100_USERS_DIM;
ALTER TABLE HS1D4P100_USERS_DIM ADD (
  CONSTRAINT HS1D4P100_USERS_PK
 PRIMARY KEY
 (USER_PROFILE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
