Prompt Non-Foreign Key Constraints on Table HS1D4P200_PERIOD_DIM;
ALTER TABLE HS1D4P200_PERIOD_DIM ADD (
  CONSTRAINT HS1D4P200_PERIOD_DIM_PK
 PRIMARY KEY
 (PERIOD_ID)
    USING INDEX 
    TABLESPACE USERS)
/
