Prompt Foreign Key Constraints on Table HS1D4P150_MOVES_FACT;
ALTER TABLE HS1D4P150_MOVES_FACT ADD (
  CONSTRAINT HS1D4P150_MOVES_MOVE_SEMS_FK 
 FOREIGN KEY (MOVE_SEMS_ID) 
 REFERENCES HS1D4P150_MOVE_SEMS_DIM (MOVE_SEMS_ID),
  CONSTRAINT HS1D4P150_MOVES_PERIOD_FK 
 FOREIGN KEY (PERIOD_ID) 
 REFERENCES HS1D4P150_PERIOD_DIM (PERIOD_ID),
  CONSTRAINT HS1D4P150_MOVES_USER_FK 
 FOREIGN KEY (USER_PROFILE_ID) 
 REFERENCES HS1D4P150_USERS_DIM (USER_PROFILE_ID),
  CONSTRAINT HS1D4P150_MOVES_FROM_STOPS_FK 
 FOREIGN KEY (FROM_STOP_SEMS_ID) 
 REFERENCES HS1D4P150_STOP_SEMS_DIM (STOP_SEMS_ID),
  CONSTRAINT HS1D4P150_MOVES_TO_STOPS_FK 
 FOREIGN KEY (TO_STOP_SEMS_ID) 
 REFERENCES HS1D4P150_STOP_SEMS_DIM (STOP_SEMS_ID))
/
