Prompt Non-Foreign Key Constraints on Table SEM_DW_STOPS_FACT;
ALTER TABLE SEM_DW_STOPS_FACT ADD (
  CONSTRAINT STOPS_FACT_PK
 PRIMARY KEY
 (PERIOD_ID, STOP_SEMS_ID, USER_PROFILE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
