Prompt Non-Foreign Key Constraints on Table SEM_TRAJS_EPIS3DGEOM;
ALTER TABLE SEM_TRAJS_EPIS3DGEOM ADD (
  CONSTRAINT SEM_TRAJS_3DGEOM_PK
 PRIMARY KEY
 (O_ID, T_ID, E_ID)
    USING INDEX 
    TABLESPACE USERS)
/
