Prompt Index ATTIKI_200_MOVES_FACT_PK;
CREATE UNIQUE INDEX ATTIKI_200_MOVES_FACT_PK ON ATTIKI_200_MOVES_FACT
(PERIOD_ID, FROM_STOP_SEMS_ID, TO_STOP_SEMS_ID, USER_PROFILE_ID, MOVE_SEMS_ID)
TABLESPACE USERS
/


