Prompt drop TABLE TEMP_ELEMENTS_MIN;
DROP TABLE TEMP_ELEMENTS_MIN CASCADE CONSTRAINTS PURGE
/

Prompt Table TEMP_ELEMENTS_MIN;
CREATE TABLE TEMP_ELEMENTS_MIN OF D_TEMP_ELEMENT_MIN 
NESTED TABLE TE STORE AS TE_MIN_TAB
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


