Prompt drop TABLE TEMP_ELEMENTS_M;
DROP TABLE TEMP_ELEMENTS_M CASCADE CONSTRAINTS PURGE
/

Prompt Table TEMP_ELEMENTS_M;
CREATE TABLE TEMP_ELEMENTS_M OF D_TEMP_ELEMENT_M 
NESTED TABLE TE STORE AS TE_M_TAB
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


