Prompt drop TABLE TEMP_ELEMENTS_D;
DROP TABLE TEMP_ELEMENTS_D CASCADE CONSTRAINTS PURGE
/

Prompt Table TEMP_ELEMENTS_D;
CREATE TABLE TEMP_ELEMENTS_D OF D_TEMP_ELEMENT_D 
NESTED TABLE TE STORE AS TE_D_TAB
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


