Prompt drop TABLE TEMP_ELEMENTS_H;
DROP TABLE TEMP_ELEMENTS_H CASCADE CONSTRAINTS PURGE
/

Prompt Table TEMP_ELEMENTS_H;
CREATE TABLE TEMP_ELEMENTS_H OF D_TEMP_ELEMENT_H 
NESTED TABLE TE STORE AS TE_H_TAB
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/


