Prompt User HERMES;
CREATE USER HERMES
  IDENTIFIED BY HERMES
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
/
  -- 16 Roles for HERMES 
  GRANT CONNECT TO HERMES
/
  GRANT JAVAUSERPRIV TO HERMES
/
  GRANT SELECT_CATALOG_ROLE TO HERMES
/
  GRANT IMP_FULL_DATABASE TO HERMES
/
  GRANT AQ_USER_ROLE TO HERMES
/
  GRANT DELETE_CATALOG_ROLE TO HERMES
/
  GRANT RECOVERY_CATALOG_OWNER TO HERMES
/
  GRANT DBA TO HERMES
/
  GRANT EXECUTE_CATALOG_ROLE TO HERMES
/
  GRANT AQ_ADMINISTRATOR_ROLE TO HERMES
/
  GRANT HS_ADMIN_ROLE TO HERMES
/
  GRANT RESOURCE TO HERMES
/
  GRANT EXP_FULL_DATABASE TO HERMES
/
  GRANT JAVASYSPRIV TO HERMES
/
  ALTER USER HERMES DEFAULT ROLE ALL
/
  -- 140 System Privileges for HERMES 
  GRANT CREATE EXTERNAL JOB TO HERMES
/
  GRANT UNDER ANY TABLE TO HERMES
/
  GRANT UNDER ANY TYPE TO HERMES
/
  GRANT EXECUTE ANY TYPE TO HERMES
/
  GRANT DROP ANY TYPE TO HERMES
/
  GRANT DROP ANY MATERIALIZED VIEW TO HERMES
/
  GRANT CREATE MATERIALIZED VIEW TO HERMES
/
  GRANT DROP PROFILE TO HERMES
/
  GRANT ALTER PROFILE TO HERMES
/
  GRANT EXECUTE ANY PROCEDURE TO HERMES
/
  GRANT FORCE ANY TRANSACTION TO HERMES
/
  GRANT CREATE ROLE TO HERMES
/
  GRANT DROP ANY INDEX TO HERMES
/
  GRANT CREATE ANY INDEX TO HERMES
/
  GRANT COMMENT ANY TABLE TO HERMES
/
  GRANT DROP USER TO HERMES
/
  GRANT CREATE TABLESPACE TO HERMES
/
  GRANT ADMINISTER ANY SQL TUNING SET TO HERMES
/
  GRANT DEBUG ANY PROCEDURE TO HERMES
/
  GRANT CREATE ANY OUTLINE TO HERMES
/
  GRANT DROP ANY DIMENSION TO HERMES
/
  GRANT GLOBAL QUERY REWRITE TO HERMES
/
  GRANT CREATE ANY LIBRARY TO HERMES
/
  GRANT CREATE ANY DIRECTORY TO HERMES
/
  GRANT CREATE ANY PROCEDURE TO HERMES
/
  GRANT DROP ANY ROLE TO HERMES
/
  GRANT BACKUP ANY TABLE TO HERMES
/
  GRANT BECOME USER TO HERMES
/
  GRANT MANAGE TABLESPACE TO HERMES
/
  GRANT AUDIT SYSTEM TO HERMES
/
  GRANT ADMINISTER SQL TUNING SET TO HERMES
/
  GRANT ALTER ANY SQL PROFILE TO HERMES
/
  GRANT SELECT ANY TRANSACTION TO HERMES
/
  GRANT EXPORT FULL DATABASE TO HERMES
/
  GRANT SELECT ANY DICTIONARY TO HERMES
/
  GRANT CREATE OPERATOR TO HERMES
/
  GRANT DROP ANY LIBRARY TO HERMES
/
  GRANT ALTER ANY LIBRARY TO HERMES
/
  GRANT CREATE ANY TYPE TO HERMES
/
  GRANT GRANT ANY PRIVILEGE TO HERMES
/
  GRANT CREATE PROFILE TO HERMES
/
  GRANT AUDIT ANY TO HERMES
/
  GRANT DROP PUBLIC DATABASE LINK TO HERMES
/
  GRANT CREATE SEQUENCE TO HERMES
/
  GRANT DROP ANY SYNONYM TO HERMES
/
  GRANT DROP ROLLBACK SEGMENT TO HERMES
/
  GRANT UNLIMITED TABLESPACE TO HERMES
/
  GRANT DROP TABLESPACE TO HERMES
/
  GRANT DROP ANY SQL PROFILE TO HERMES
/
  GRANT ANALYZE ANY DICTIONARY TO HERMES
/
  GRANT ADMINISTER DATABASE TRIGGER TO HERMES
/
  GRANT CREATE DIMENSION TO HERMES
/
  GRANT CREATE ANY OPERATOR TO HERMES
/
  GRANT EXECUTE ANY LIBRARY TO HERMES
/
  GRANT ALTER ANY TYPE TO HERMES
/
  GRANT ALTER ANY MATERIALIZED VIEW TO HERMES
/
  GRANT ALTER ANY PROCEDURE TO HERMES
/
  GRANT CREATE DATABASE LINK TO HERMES
/
  GRANT CREATE PUBLIC SYNONYM TO HERMES
/
  GRANT ALTER ANY CLUSTER TO HERMES
/
  GRANT CREATE CLUSTER TO HERMES
/
  GRANT DELETE ANY TABLE TO HERMES
/
  GRANT UPDATE ANY TABLE TO HERMES
/
  GRANT LOCK ANY TABLE TO HERMES
/
  GRANT CREATE JOB TO HERMES
/
  GRANT ADVISOR TO HERMES
/
  GRANT GRANT ANY OBJECT PRIVILEGE TO HERMES
/
  GRANT EXEMPT ACCESS POLICY TO HERMES
/
  GRANT DROP ANY OUTLINE TO HERMES
/
  GRANT CREATE ANY DIMENSION TO HERMES
/
  GRANT EXECUTE ANY INDEXTYPE TO HERMES
/
  GRANT UNDER ANY VIEW TO HERMES
/
  GRANT EXECUTE ANY OPERATOR TO HERMES
/
  GRANT CREATE LIBRARY TO HERMES
/
  GRANT DROP ANY PROCEDURE TO HERMES
/
  GRANT ALTER ANY ROLE TO HERMES
/
  GRANT ALTER ANY SEQUENCE TO HERMES
/
  GRANT CREATE ANY VIEW TO HERMES
/
  GRANT DROP PUBLIC SYNONYM TO HERMES
/
  GRANT CREATE ANY SYNONYM TO HERMES
/
  GRANT CREATE SYNONYM TO HERMES
/
  GRANT ALTER ANY INDEX TO HERMES
/
  GRANT CREATE ANY CLUSTER TO HERMES
/
  GRANT CREATE ROLLBACK SEGMENT TO HERMES
/
  GRANT RESTRICTED SESSION TO HERMES
/
  GRANT CREATE ANY SQL PROFILE TO HERMES
/
  GRANT EXECUTE ANY CLASS TO HERMES
/
  GRANT EXECUTE ANY PROGRAM TO HERMES
/
  GRANT ON COMMIT REFRESH TO HERMES
/
  GRANT ALTER ANY OUTLINE TO HERMES
/
  GRANT CREATE ANY CONTEXT TO HERMES
/
  GRANT ALTER ANY DIMENSION TO HERMES
/
  GRANT QUERY REWRITE TO HERMES
/
  GRANT DROP ANY INDEXTYPE TO HERMES
/
  GRANT CREATE ANY INDEXTYPE TO HERMES
/
  GRANT CREATE TYPE TO HERMES
/
  GRANT DROP ANY DIRECTORY TO HERMES
/
  GRANT CREATE TRIGGER TO HERMES
/
  GRANT GRANT ANY ROLE TO HERMES
/
  GRANT DROP ANY VIEW TO HERMES
/
  GRANT DROP ANY CLUSTER TO HERMES
/
  GRANT INSERT ANY TABLE TO HERMES
/
  GRANT CREATE TABLE TO HERMES
/
  GRANT ALTER USER TO HERMES
/
  GRANT ALTER SESSION TO HERMES
/
  GRANT EXEMPT IDENTITY POLICY TO HERMES
/
  GRANT FLASHBACK ANY TABLE TO HERMES
/
  GRANT DEBUG CONNECT SESSION TO HERMES
/
  GRANT RESUMABLE TO HERMES
/
  GRANT DROP ANY CONTEXT TO HERMES
/
  GRANT ALTER ANY INDEXTYPE TO HERMES
/
  GRANT ANALYZE ANY TO HERMES
/
  GRANT ALTER RESOURCE COST TO HERMES
/
  GRANT ALTER DATABASE TO HERMES
/
  GRANT CREATE PUBLIC DATABASE LINK TO HERMES
/
  GRANT SELECT ANY SEQUENCE TO HERMES
/
  GRANT ALTER ROLLBACK SEGMENT TO HERMES
/
  GRANT CREATE USER TO HERMES
/
  GRANT ALTER TABLESPACE TO HERMES
/
  GRANT ALTER SYSTEM TO HERMES
/
  GRANT MANAGE SCHEDULER TO HERMES
/
  GRANT CREATE ANY JOB TO HERMES
/
  GRANT IMPORT FULL DATABASE TO HERMES
/
  GRANT CREATE INDEXTYPE TO HERMES
/
  GRANT DROP ANY OPERATOR TO HERMES
/
  GRANT ALTER ANY OPERATOR TO HERMES
/
  GRANT CREATE ANY MATERIALIZED VIEW TO HERMES
/
  GRANT DROP ANY TRIGGER TO HERMES
/
  GRANT ALTER ANY TRIGGER TO HERMES
/
  GRANT CREATE ANY TRIGGER TO HERMES
/
  GRANT CREATE PROCEDURE TO HERMES
/
  GRANT FORCE TRANSACTION TO HERMES
/
  GRANT DROP ANY SEQUENCE TO HERMES
/
  GRANT CREATE ANY SEQUENCE TO HERMES
/
  GRANT CREATE VIEW TO HERMES
/
  GRANT SELECT ANY TABLE TO HERMES
/
  GRANT DROP ANY TABLE TO HERMES
/
  GRANT ALTER ANY TABLE TO HERMES
/
  GRANT CREATE ANY TABLE TO HERMES
/
  GRANT CREATE SESSION TO HERMES
/
  -- 4 Java Privileges for HERMES 
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'HERMES'
    ,permission_type   => 'SYS:java.io.FilePermission'
    ,permission_name   => '<<ALL FILES>>'
    ,permission_action => 'read ,write, execute, delete'
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'HERMES'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'writeFileDescriptor'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'HERMES'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'readFileDescriptor'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/
DECLARE
 KEYNUM NUMBER;
BEGIN
  SYS.DBMS_JAVA.GRANT_PERMISSION(
     grantee           => 'HERMES'
    ,permission_type   => 'SYS:java.lang.RuntimePermission'
    ,permission_name   => 'getenv.*'
    ,permission_action => ''
    ,key               => KEYNUM
    );
END;
/


