Prompt Table A_ATTIKI_PERIOD_DIM;
CREATE TABLE A_ATTIKI_PERIOD_DIM
(
  PERIOD_ID   NUMBER(9)                         NOT NULL,
  TIMEPERIOD  TAU_TLL.D_PERIOD_SEC,
  RUSHHOUR    TAU_TLL.D_PERIOD_SEC,
  PARTOFDAY   VARCHAR2(50 BYTE)
)
COLUMN TIMEPERIOD NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN RUSHHOUR NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


