Prompt Table A_ATTIKI_STOP_SEMS_DIM;
CREATE TABLE A_ATTIKI_STOP_SEMS_DIM
(
  STOP_SEMS_ID   NUMBER(9),
  STOP_TYPE      VARCHAR2(50 BYTE),
  STOP_ACTIVITY  VARCHAR2(50 BYTE),
  POI_ID         NUMBER(9),
  STOP_NAME      VARCHAR2(70 BYTE)
)
TABLESPACE USERS
/


