Prompt Table ATTIKI_INPUT;
CREATE TABLE ATTIKI_INPUT
(
  OBJECT_ID           INTEGER,
  SEM_TRAJ_ID         INTEGER,
  EPIS_ID             INTEGER,
  SEM_TRAJ_TAG        VARCHAR2(8 BYTE),
  SRID                INTEGER,
  EPIS_DEF_TAG        VARCHAR2(6 BYTE),
  EPIS_EPIS_TAG       VARCHAR2(30 BYTE),
  EPIS_ACTIV_TAG      VARCHAR2(30 BYTE),
  EPIS_MINX           INTEGER,
  EPIS_MINY           INTEGER,
  EPIS_MINYEAR        INTEGER,
  EPIS_MINMONTH       INTEGER,
  EPIS_MINDAY         INTEGER,
  EPIS_MINHOUR        INTEGER,
  EPIS_MINMINUTE      INTEGER,
  EPIS_MINSECOND      INTEGER,
  EPIS_MAXX           INTEGER,
  EPIS_MAXY           INTEGER,
  EPIS_MAXYEAR        INTEGER,
  EPIS_MAXMONTH       INTEGER,
  EPIS_MAXDAY         INTEGER,
  EPIS_MAXHOUR        INTEGER,
  EPIS_MAXMINUTE      INTEGER,
  EPIS_MAXSECOND      INTEGER,
  DISTANCE_COVERED    INTEGER,
  DURATION_SEC        INTEGER,
  TOP_SPEED           INTEGER,
  AVG_SPEED           FLOAT(126),
  SPEED_VAR           FLOAT(126),
  NUMBER_OF_PROFILES  FLOAT(126),
  MBR                 MDSYS.SDO_GEOMETRY
)
COLUMN MBR NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


