Prompt Table ATTIKI_CENTER_RECTANGLE;
CREATE TABLE ATTIKI_CENTER_RECTANGLE
(
  GEOGRAPHYID  NUMBER(22,2)                     NOT NULL,
  RECGEO       MDSYS.SDO_GEOMETRY,
  X_DL         NUMBER(22,10),
  Y_DL         NUMBER(22,10),
  X_UR         NUMBER(22,10),
  Y_UR         NUMBER(22,10)
)
COLUMN RECGEO NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


