Prompt Table ATTIKI_200_TIME_DIM;
CREATE TABLE ATTIKI_200_TIME_DIM
(
  TIME_ID    NUMBER(9)                          NOT NULL,
  TIMEPOINT  TAU_TLL.D_TIMEPOINT_SEC,
  HOUR       NUMBER(2),
  DAY        NUMBER(2),
  MONTH      NUMBER(2),
  YEAR       NUMBER(4),
  QUARTER    NUMBER(1),
  DAYOFWEEK  VARCHAR2(50 BYTE)
)
COLUMN TIMEPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


