Prompt Table ATTIKI_POIS_FROM_STOPS;
CREATE TABLE ATTIKI_POIS_FROM_STOPS
(
  ID         NUMBER,
  NAME       VARCHAR2(44 BYTE),
  TYPE       VARCHAR2(50 BYTE),
  CITY       CHAR(6 BYTE),
  COUNTRY    CHAR(6 BYTE),
  ACTIVITY   VARCHAR2(50 BYTE),
  LATITUDE   NUMBER,
  LONGITUDE  NUMBER,
  POI_GEOM   MDSYS.SDO_GEOMETRY,
  DISTRICT   VARCHAR2(30 BYTE),
  STATE      VARCHAR2(30 BYTE)
)
COLUMN POI_GEOM NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


