Prompt Table ATTIKI_CEN_PERTRAJ;
CREATE TABLE ATTIKI_CEN_PERTRAJ
(
  OBJECT_ID         INTEGER,
  TRAJ_ID           INTEGER,
  STARTLOC          MDSYS.SDO_GEOMETRY,
  ENDLOC            MDSYS.SDO_GEOMETRY,
  MBB               SEM_MBB,
  DURATION          NUMBER,
  LENGTH            NUMBER,
  AVGSPEED          NUMBER,
  NUMOFPOINTS       INTEGER,
  RADIUSOFGYRATION  NUMBER
)
COLUMN STARTLOC NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN ENDLOC NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN MBB NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


