Prompt Table ATTIKI_200_USERS_DIM;
CREATE TABLE ATTIKI_200_USERS_DIM
(
  USER_PROFILE_ID  NUMBER(9),
  DEVICE_TYPE      VARCHAR2(60 BYTE),
  GENDER           VARCHAR2(6 BYTE),
  BIRTHDAY         TIMESTAMP(6),
  PROFESSION       VARCHAR2(50 BYTE),
  MARITAL_STATUS   VARCHAR2(20 BYTE)
)
TABLESPACE USERS
/


