Prompt Table ATTIKI_CENTER_MPOINTS;
CREATE TABLE ATTIKI_CENTER_MPOINTS
(
  OBJECT_ID  INTEGER,
  TRAJ_ID    INTEGER,
  MPOINT     MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


