Prompt Table BELGSUB_STOPS_MPOINTS;
CREATE TABLE BELGSUB_STOPS_MPOINTS
(
  OBJECT_ID   INTEGER,
  TRAJ_ID     INTEGER,
  MPOINT      MOVING_POINT,
  SUBTRAJ_ID  INTEGER,
  STOP_ID     INTEGER
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


