Prompt drop TABLE BELG_TOPTICS_CHECK;
DROP TABLE BELG_TOPTICS_CHECK CASCADE CONSTRAINTS PURGE
/

Prompt Table BELG_TOPTICS_CHECK;
CREATE TABLE BELG_TOPTICS_CHECK
(
  OBJECT_ID    INTEGER,
  TRAJ_ID      INTEGER,
  MPOINT       MOVING_POINT,
  DESCRIPTION  VARCHAR2(100 BYTE)
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
LOB ("MPOINT"."U_TAB") STORE AS 
      ( TABLESPACE  USERS 
        ENABLE      STORAGE IN ROW
        CHUNK       8192
        PCTVERSION  10
        CACHE
        INDEX       (
          TABLESPACE USERS)
      )
/


