Prompt Table BRINKHOFF_OUTPUT;
CREATE TABLE BRINKHOFF_OUTPUT
(
  DESCR      VARCHAR2(50 BYTE),
  ID         NUMBER,
  REPNUM     NUMBER,
  CLASSID    NUMBER,
  TIME       NUMBER,
  EDGEID     NUMBER,
  X          NUMBER,
  Y          NUMBER,
  SPEED      NUMBER,
  DONEDIST   NUMBER,
  NEXTNODEX  NUMBER,
  NEXTNODEY  NUMBER
)
TABLESPACE USERS
/


