Prompt drop TABLE BRINKHOFF_SEMTRAJS;
DROP TABLE BRINKHOFF_SEMTRAJS CASCADE CONSTRAINTS PURGE
/

Prompt Table BRINKHOFF_SEMTRAJS;
CREATE TABLE BRINKHOFF_SEMTRAJS OF SEM_TRAJECTORY 
NESTED TABLE EPISODES STORE AS BRINKHOFF_EPISODES
TABLESPACE USERS
/


