Prompt Table BRINKHOFF_POIS;
CREATE TABLE BRINKHOFF_POIS
(
  ID          NUMBER,
  NAME        VARCHAR2(100 BYTE),
  TYPE        VARCHAR2(100 BYTE),
  LONGITUDE   NUMBER,
  LATITUDE    NUMBER,
  X           NUMBER,
  Y           NUMBER,
  NN_NODE_ID  NUMBER,
  POI_GEOM    MDSYS.SDO_GEOMETRY
)
COLUMN POI_GEOM NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


