Prompt Table DATAFORSTATISTICGRAPHS;
CREATE TABLE DATAFORSTATISTICGRAPHS
(
  CATEGORY     NUMBER,
  SERIES1      NUMBER,
  SERIES2      NUMBER,
  SERIES3      NUMBER,
  XDATA        NUMBER,
  YDATA        NUMBER,
  TIMESTAMP    TIMESTAMP(0),
  DESCRIPTION  VARCHAR2(50 BYTE)
)
TABLESPACE USERS
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.CATEGORY IS 'category for statistical graphs with one or more categories'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.SERIES1 IS 'series 1 values for specific category'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.SERIES2 IS 'series 2 values for specific category'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.SERIES3 IS 'series 3 values for specific category'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.XDATA IS 'x values for xy-graphs'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.YDATA IS 'y values for xy-graphs'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.TIMESTAMP IS 'a timestamp for a value'
/

COMMENT ON COLUMN DATAFORSTATISTICGRAPHS.DESCRIPTION IS 'a description for columns'
/


