Prompt Table IMIS_STOPS;
CREATE TABLE IMIS_STOPS
(
  USERID  VARCHAR2(9 BYTE),
  TRAJ    VARCHAR2(12 BYTE),
  X       NUMBER(13,6),
  Y       NUMBER(14,6),
  TIME    NUMBER(12),
  STOPID  NUMBER(2)
)
TABLESPACE USERS
/


