Prompt Table IMIS_3DAYS_PORTS;
CREATE TABLE IMIS_3DAYS_PORTS
(
  NAME       VARCHAR2(100 BYTE),
  LONGITUDE  NUMBER,
  LATITUDE   NUMBER,
  X          NUMBER,
  Y          NUMBER,
  GEOM       MDSYS.SDO_GEOMETRY
)
COLUMN GEOM NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


