Prompt drop TABLE PLSQL_PROFILER_UNITS;
ALTER TABLE PLSQL_PROFILER_UNITS
 DROP PRIMARY KEY CASCADE
/

DROP TABLE PLSQL_PROFILER_UNITS CASCADE CONSTRAINTS PURGE
/

Prompt Table PLSQL_PROFILER_UNITS;
CREATE TABLE PLSQL_PROFILER_UNITS
(
  RUNID           NUMBER,
  UNIT_NUMBER     NUMBER,
  UNIT_TYPE       VARCHAR2(32 BYTE),
  UNIT_OWNER      VARCHAR2(32 BYTE),
  UNIT_NAME       VARCHAR2(32 BYTE),
  UNIT_TIMESTAMP  DATE,
  TOTAL_TIME      NUMBER                        DEFAULT 0                     NOT NULL,
  SPARE1          NUMBER,
  SPARE2          NUMBER
)
TABLESPACE USERS
/

COMMENT ON TABLE PLSQL_PROFILER_UNITS IS 'Information about each library unit in a run'
/


