Prompt Table SEM_MPOINT_RAW;
CREATE TABLE SEM_MPOINT_RAW
(
  USERID        INTEGER,
  TRAJECTORYID  INTEGER,
  X             NUMBER(22,6),
  Y             NUMBER(22,6),
  YEAR          NUMBER(10),
  MONTH         NUMBER(10),
  DAY           NUMBER(10),
  HOUR          NUMBER(10),
  MINUTE        NUMBER(10),
  SECOND        NUMBER
)
TABLESPACE USERS
/


