Prompt Table A_ATTIKI_STOPS_FACT;
CREATE TABLE A_ATTIKI_STOPS_FACT
(
  PERIOD_ID                NUMBER(9),
  STOP_SEMS_ID             NUMBER(9),
  USER_PROFILE_ID          NUMBER(9),
  NUM_OF_SEM_TRAJECTORIES  INTEGER,
  NUM_OF_USERS             INTEGER,
  NUM_OF_ACTIVITIES        INTEGER,
  AVG_DURATION             NUMBER,
  RADIUS_OF_GYRATION       NUMBER,
  CROSST                   NUMBER
)
TABLESPACE USERS
/


