Prompt Table ATTIKI_USERS;
CREATE TABLE ATTIKI_USERS
(
  ID              NUMBER,
  DEVICE_TYPE     VARCHAR2(20 BYTE),
  GENDER          VARCHAR2(20 BYTE),
  BIRTHYEAR       VARCHAR2(20 BYTE),
  PROFESSION      VARCHAR2(20 BYTE),
  MARITAL_STATUS  VARCHAR2(20 BYTE)
)
TABLESPACE USERS
/


