Prompt Table ATTIKI_STBTREE_TAGS;
CREATE TABLE ATTIKI_STBTREE_TAGS
(
  TAG    VARCHAR2(50 BYTE),
  NODES  SEM_STBLEAFENTRYIDS
)
NESTED TABLE NODES STORE AS ATTIKI_STBTREE_NODES_NTAB
TABLESPACE USERS
/


