Prompt Table ATTIKI_200_MOVES_FACT;
CREATE TABLE ATTIKI_200_MOVES_FACT
(
  PERIOD_ID                NUMBER(9),
  FROM_STOP_SEMS_ID        NUMBER(9),
  TO_STOP_SEMS_ID          NUMBER(9),
  USER_PROFILE_ID          NUMBER(9),
  MOVE_SEMS_ID             NUMBER(9),
  NUM_OF_SEM_TRAJECTORIES  INTEGER,
  NUM_OF_USERS             INTEGER,
  NUM_OF_ACTIVITIES        INTEGER,
  AVG_DISTANCE_TRAVELED    NUMBER,
  AVG_TRAVEL_DURATION      NUMBER,
  AVG_SPEED                NUMBER,
  AVG_ABS_ACCELERATION     NUMBER,
  RADIUS_OF_GYRATION       NUMBER,
  CROSST                   NUMBER
)
TABLESPACE USERS
/


