Prompt Table ATTIKI_SAMPLING_TDTR;
CREATE TABLE ATTIKI_SAMPLING_TDTR
(
  OBJECT_ID  NUMBER,
  TRAJ_ID    NUMBER,
  MPOINT     MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


