Prompt Table ATTIKI_REPORTER_EXT;
CREATE TABLE ATTIKI_REPORTER_EXT
(
  ID      NUMBER,
  NUM     NUMBER,
  TIME    NUMBER,
  CLASS   NUMBER,
  X       NUMBER,
  Y       NUMBER,
  DBTIME  DATE,
  WIDTH   INTEGER,
  HEIGHT  INTEGER
)
TABLESPACE USERS
/


