Prompt Table ATTIKI_200_MOVE_SEMS_DIM;
CREATE TABLE ATTIKI_200_MOVE_SEMS_DIM
(
  MOVE_SEMS_ID   NUMBER(9),
  ROUTE_TYPE     VARCHAR2(50 BYTE),
  MOVE_MODE      VARCHAR2(50 BYTE),
  MOVE_ACTIVITY  VARCHAR2(50 BYTE)
)
TABLESPACE USERS
/


