Prompt Table ATTIKI_200_SPACE_DIM;
CREATE TABLE ATTIKI_200_SPACE_DIM
(
  POI_ID    NUMBER(9),
  POI_GEOM  MDSYS.SDO_GEOMETRY,
  DISTRICT  VARCHAR2(50 BYTE),
  CITY      VARCHAR2(50 BYTE),
  STATE     VARCHAR2(50 BYTE),
  COUNTRY   VARCHAR2(50 BYTE)
)
COLUMN POI_GEOM NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


