Prompt Table ATTIKI_MPOINTS_TBTREE_LEAF;
CREATE TABLE ATTIKI_MPOINTS_TBTREE_LEAF
(
  R     INTEGER,
  ROID  VARCHAR2(20 BYTE),
  NODE  TBTREELEAF
)
COLUMN NODE NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


