Prompt Table ATTIKI_INPUT_MPOINTS;
CREATE TABLE ATTIKI_INPUT_MPOINTS
(
  OBJECT_ID  INTEGER                            NOT NULL,
  TRAJ_ID    INTEGER                            NOT NULL,
  MPOINT     MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


