Prompt Table ATTIKI_NETWORK_EDGES;
CREATE TABLE ATTIKI_NETWORK_EDGES
(
  ID          NUMBER(5),
  A           NUMBER(9),
  B           NUMBER(9),
  DISTANCE    NUMBER(3),
  LINKTYPE    NUMBER(1),
  JURISDICTI  NUMBER(1),
  SPEED       NUMBER(2),
  CAPACITY    NUMBER(3),
  SFC         NUMBER(2)
)
TABLESPACE USERS
/


