Prompt Table ATTIKI_CLUSTER_EXT;
CREATE TABLE ATTIKI_CLUSTER_EXT
(
  CLUST_ID  NUMBER,
  TRAJ_ID   NUMBER,
  MPOINT    MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


