Prompt Table ATTIKI_POIS_DISTRICTS;
CREATE TABLE ATTIKI_POIS_DISTRICTS
(
  ID             NUMBER,
  DISTRICT       VARCHAR2(50 BYTE),
  DISTRICT_GEOM  MDSYS.SDO_GEOMETRY
)
COLUMN DISTRICT_GEOM NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


