Prompt Table ATTIKI_CENTR_I_FCM_EXT;
CREATE TABLE ATTIKI_CENTR_I_FCM_EXT
(
  CLUST_ID  NUMBER,
  TRAJ_ID   NUMBER,
  MPOINT    MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


