Prompt Table ATTIKI_STBTREE_LEAF;
CREATE TABLE ATTIKI_STBTREE_LEAF
(
  LID   INTEGER,
  ROID  VARCHAR2(32 BYTE),
  LEAF  SEM_STBLEAF
)
COLUMN LEAF NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


