Prompt Table BELG_USERS;
CREATE TABLE BELG_USERS
(
  ID              NUMBER,
  GENDER          VARCHAR2(10 BYTE),
  BIRTHYEAR       NUMBER,
  MARITAL_STATUS  VARCHAR2(50 BYTE),
  PROFESSION      VARCHAR2(50 BYTE)
)
TABLESPACE USERS
/


