Prompt Table BELG_POIS;
CREATE TABLE BELG_POIS
(
  ID         NUMBER,
  NAME       VARCHAR2(50 BYTE),
  TYPE       VARCHAR2(50 BYTE),
  DISTRICT   VARCHAR2(50 BYTE),
  CITY       VARCHAR2(50 BYTE),
  STATE      VARCHAR2(50 BYTE),
  COUNTRY    VARCHAR2(50 BYTE),
  ACTIVITY   VARCHAR2(50 BYTE),
  LATITUDE   NUMBER(8,6),
  LONGITUDE  NUMBER(8,6)
)
TABLESPACE USERS
/


