Prompt Table BRINKHOFF_INPUT_SEMTRAJS;
CREATE TABLE BRINKHOFF_INPUT_SEMTRAJS
(
  OBJECT_ID           INTEGER,
  SEM_TRAJ_ID         INTEGER,
  EPIS_ID             NUMBER,
  SEM_TRAJ_TAG        VARCHAR2(50 BYTE),
  SRID                INTEGER,
  DEFINING_TAG        VARCHAR2(4 BYTE),
  EPIS_EPIS_TAG       VARCHAR2(50 BYTE),
  EPIS_ACTIV_TAG      VARCHAR2(50 BYTE),
  EPIS_MINX           NUMBER,
  EPIS_MINY           NUMBER,
  EPIS_MINYEAR        INTEGER,
  EPIS_MINMONTH       INTEGER,
  EPIS_MINDAY         INTEGER,
  EPIS_MINHOUR        INTEGER,
  EPIS_MINMINUTE      INTEGER,
  EPIS_MINSECOND      FLOAT(126),
  EPIS_MAXX           NUMBER,
  EPIS_MAXY           NUMBER,
  EPIS_MAXYEAR        INTEGER,
  EPIS_MAXMONTH       INTEGER,
  EPIS_MAXDAY         INTEGER,
  EPIS_MAXHOUR        INTEGER,
  EPIS_MAXMINUTE      INTEGER,
  EPIS_MAXSECOND      FLOAT(126),
  DISTANCE_COVERED    NUMBER,
  DURATION_SEC        NUMBER,
  TOP_SPEED           NUMBER,
  AVG_SPEED           NUMBER,
  SPEED_VAR           NUMBER,
  NUMBER_OF_PROFILES  NUMBER
)
TABLESPACE USERS
/


