Prompt Table BRINKHOFF_INFO;
CREATE TABLE BRINKHOFF_INFO
(
  RESOLUTION  NUMBER,
  MINX        NUMBER,
  MAXY        NUMBER,
  DX          NUMBER,
  DY          NUMBER,
  SRID        NUMBER
)
TABLESPACE USERS
/


