Prompt Table DBMSOUTPUT;
CREATE TABLE DBMSOUTPUT
(
  MESSAGE   VARCHAR2(4000 BYTE),
  A         NUMBER,
  B         NUMBER,
  C         NUMBER,
  D         NUMBER,
  E         NUMBER,
  MESSAGE2  VARCHAR2(4000 BYTE),
  TIMER     TIMESTAMP(6)
)
TABLESPACE USERS
/


