Prompt Table FAKES;
CREATE TABLE FAKES
(
  USER_ID  NUMBER                               NOT NULL,
  TRAJ_ID  INTEGER                              NOT NULL,
  MPOINT   MOVING_POINT,
  K_PARAM  NUMBER
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


