Prompt Table HIST;
CREATE TABLE HIST
(
  USER_ID  NUMBER                               NOT NULL,
  ID       NUMBER                               NOT NULL,
  GEOM     MDSYS.SDO_GEOMETRY,
  TA       TAU_TLL.D_TIMEPOINT_SEC,
  TB       TAU_TLL.D_TIMEPOINT_SEC
)
COLUMN GEOM NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN TA NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN TB NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


