Prompt Table HIST_CLUSTER_TABLE;
CREATE TABLE HIST_CLUSTER_TABLE
(
  TABLE_NAME          VARCHAR2(50 BYTE)         NOT NULL,
  CLUSTER_ID          NUMBER                    NOT NULL,
  MOVING_POINT_COUNT  NUMBER
)
TABLESPACE USERS
/


