Prompt Table HPV_RESULT2;
CREATE TABLE HPV_RESULT2
(
  TRAJ_ID  INTEGER                              NOT NULL,
  MPOINT   MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


