Prompt Table IMIS_3DAYS_TAG_EPIS_INDX;
CREATE TABLE IMIS_3DAYS_TAG_EPIS_INDX
(
  TAG    VARCHAR2(50 BYTE),
  NODES  SEM_STBLEAFENTRYIDS
)
NESTED TABLE NODES STORE AS IMIS_3DAYS_NODES_NTAB
TABLESPACE USERS
/


