Prompt Table IMIS_3DAYS_GLOBAL;
CREATE TABLE IMIS_3DAYS_GLOBAL
(
  MINX        NUMBER,
  MAXX        NUMBER,
  MINY        NUMBER,
  MAXY        NUMBER,
  MINT        TIMESTAMP(6),
  MAXT        TIMESTAMP(6),
  SRID        INTEGER,
  NUMOFTRAJS  INTEGER
)
TABLESPACE USERS
/


