Prompt Table INIT_END;
CREATE TABLE INIT_END
(
  USER_ID     NUMBER                            NOT NULL,
  TRAJ_ID     INTEGER                           NOT NULL,
  INIT_POINT  UNIT_MOVING_POINT,
  END_POINT   UNIT_MOVING_POINT
)
COLUMN INIT_POINT NOT SUBSTITUTABLE AT ALL LEVELS
COLUMN END_POINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


