Prompt Table SEM_DW_TMP_MOVES_FACT;
CREATE TABLE SEM_DW_TMP_MOVES_FACT
(
  USER_ID             NUMBER(9),
  SEMTRAJ_ID          NUMBER(9),
  PERIOD_ID           NUMBER(9),
  FROM_STOP_SEMS_ID   NUMBER(9),
  TO_STOP_SEMS_ID     NUMBER(9),
  USER_PROFILE_ID     NUMBER(9),
  MOVE_SEMS_ID        NUMBER(9),
  ACTIVITY            VARCHAR2(50 BYTE),
  DISTANCE_TRAVELED   NUMBER,
  DURATION            NUMBER,
  SPEED               NUMBER,
  ACCELERATION        NUMBER,
  RADIUS_OF_GYRATION  NUMBER
)
TABLESPACE USERS
/


