Prompt Table SEM_MPOINT_FROM_RAW;
CREATE TABLE SEM_MPOINT_FROM_RAW
(
  OBJECT_ID  INTEGER,
  TRAJ_ID    INTEGER,
  MPOINT     MOVING_POINT
)
COLUMN MPOINT NOT SUBSTITUTABLE AT ALL LEVELS
TABLESPACE USERS
/


