Prompt Table TMPFACTTBL;
CREATE TABLE TMPFACTTBL
(
  TIME_ID            INTEGER,
  SPACE_ID           INTEGER,
  USERPROFILE_ID     INTEGER,
  DISTANCE_TRAVELED  NUMBER(22,2),
  TIME_DURATION      INTEGER,
  SPEED              INTEGER,
  ACCELERATION       INTEGER,
  OBJ_ID             INTEGER,
  TRAJ_ID            INTEGER
)
TABLESPACE USERS
/


