Prompt drop TABLE TOAD_HEALTH_CHECK;
DROP TABLE TOAD_HEALTH_CHECK CASCADE CONSTRAINTS PURGE
/

Prompt Table TOAD_HEALTH_CHECK;
CREATE TABLE TOAD_HEALTH_CHECK
(
  DATABASE_NAME       VARCHAR2(100 BYTE),
  METRIC_DESCRIPTION  VARCHAR2(100 BYTE),
  METRIC_DATE         DATE,
  BAD_FLAG            CHAR(1 BYTE),
  METRIC_DATA_1       VARCHAR2(300 BYTE),
  METRIC_DATA_2       VARCHAR2(300 BYTE),
  METRIC_DATA_3       VARCHAR2(300 BYTE),
  METRIC_DATA_4       VARCHAR2(300 BYTE)
)
TABLESPACE USERS
/


