Prompt drop DIRECTORY ORACLE_OCM_CONFIG_DIR;
DROP DIRECTORY ORACLE_OCM_CONFIG_DIR
/

Prompt Directory ORACLE_OCM_CONFIG_DIR;
CREATE OR REPLACE DIRECTORY 
ORACLE_OCM_CONFIG_DIR AS 
'C:\app\stylianos\product\11.2.0\dbhome_1\ccr\state'
/


