Prompt Foreign Key Constraints on Table A_ATTIKI_STOPS_FACT;
ALTER TABLE A_ATTIKI_STOPS_FACT ADD (
  CONSTRAINT STOPS_FACT_USER_FK 
 FOREIGN KEY (USER_PROFILE_ID) 
 REFERENCES A_ATTIKI_USER_PROFILE_DIM (USER_PROFILE_ID),
  CONSTRAINT STOPS_FACT_PERIOD_FK 
 FOREIGN KEY (PERIOD_ID) 
 REFERENCES A_ATTIKI_PERIOD_DIM (PERIOD_ID),
  CONSTRAINT STOPS_FACT_STOP_SEMS_FK 
 FOREIGN KEY (STOP_SEMS_ID) 
 REFERENCES A_ATTIKI_STOP_SEMS_DIM (STOP_SEMS_ID))
/
