Prompt Foreign Key Constraints on Table A_ATTIKI_MOVES_FACT;
ALTER TABLE A_ATTIKI_MOVES_FACT ADD (
  CONSTRAINT MOVES_FACT_TO_STOPS_FK 
 FOREIGN KEY (TO_STOP_SEMS_ID) 
 REFERENCES A_ATTIKI_STOP_SEMS_DIM (STOP_SEMS_ID),
  CONSTRAINT MOVES_FACT_FROM_STOPS_FK 
 FOREIGN KEY (FROM_STOP_SEMS_ID) 
 REFERENCES A_ATTIKI_STOP_SEMS_DIM (STOP_SEMS_ID),
  CONSTRAINT MOVES_FACT_USER_FK 
 FOREIGN KEY (USER_PROFILE_ID) 
 REFERENCES A_ATTIKI_USER_PROFILE_DIM (USER_PROFILE_ID),
  CONSTRAINT MOVES_FACT_PERIOD_FK 
 FOREIGN KEY (PERIOD_ID) 
 REFERENCES A_ATTIKI_PERIOD_DIM (PERIOD_ID),
  CONSTRAINT MOVES_FACT_MOVE_SEMS_FK 
 FOREIGN KEY (MOVE_SEMS_ID) 
 REFERENCES A_ATTIKI_MOVE_SEMS_DIM (MOVE_SEMS_ID))
/
