Prompt Non-Foreign Key Constraints on Table ATTIKI_200_PERIOD_DIM;
ALTER TABLE ATTIKI_200_PERIOD_DIM ADD (
  CONSTRAINT ATTIKI_200_PERIOD_DIM_PK
 PRIMARY KEY
 (PERIOD_ID)
    USING INDEX 
    TABLESPACE USERS)
/
