Prompt Non-Foreign Key Constraints on Table ATTIKI_200_STOPS_FACT;
ALTER TABLE ATTIKI_200_STOPS_FACT ADD (
  CONSTRAINT ATTIKI_200_STOPS_FACT_PK
 PRIMARY KEY
 (PERIOD_ID, STOP_SEMS_ID, USER_PROFILE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
