Prompt Non-Foreign Key Constraints on Table SEM_DW_STOP_SEMS_DIM;
ALTER TABLE SEM_DW_STOP_SEMS_DIM ADD (
  CONSTRAINT STOPS_SEMS_PK
 PRIMARY KEY
 (STOP_SEMS_ID)
    USING INDEX 
    TABLESPACE USERS)
/
