Prompt Non-Foreign Key Constraints on Table SEM_DW_USER_PROFILE_DIM;
ALTER TABLE SEM_DW_USER_PROFILE_DIM ADD (
  CONSTRAINT USER_PROFILE_PK
 PRIMARY KEY
 (USER_PROFILE_ID)
    USING INDEX 
    TABLESPACE USERS)
/
